language: node_js

os:
  - linux

node_js:
  - "node"

env:
  global:
    - ELM_VERSION=0.18.0
    - ELM_TEST_VERSION=^0.18.12

addons:
  apt:
    packages:
      - python3

install:
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST_VERSION elm-format@exp

script:
  - elm-format --validate src tests
  - make all test

before_deploy: make data

deploy:
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  project-name: who
  provider: pages
  skip-cleanup: true
  on:
    branch: master
