language: node_js

os:
  - osx

node_js:
  - "node"

script:
  - make all test
  - npx elm-format --validate src tests

before_deploy:
  - brew install python3 pipenv || true
  - pipenv install --dev
  - URL_BASE="/who" make -e data api-base all

deploy:
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  project-name: who
  provider: pages
  skip-cleanup: true
  on:
    branch: master
